In [1]:
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
# from sklearn.model_selection import train_test_split

In [2]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
data1 = pd.read_csv("Diabetes_XTrain.csv")

In [53]:
X_train=data1.values

In [54]:
X_train

array([[  7.   , 168.   ,  88.   , ...,  38.2  ,   0.787,  40.   ],
       [  8.   , 110.   ,  76.   , ...,  27.8  ,   0.237,  58.   ],
       [  7.   , 147.   ,  76.   , ...,  39.4  ,   0.257,  43.   ],
       ...,
       [  2.   , 122.   ,  60.   , ...,  29.8  ,   0.717,  22.   ],
       [  4.   , 154.   ,  72.   , ...,  31.3  ,   0.338,  37.   ],
       [  1.   ,  88.   ,  78.   , ...,  32.   ,   0.365,  29.   ]])

In [55]:
data2 = pd.read_csv("Diabetes_YTrain.csv")

In [56]:
y_train =  data2.values
y_train = y_train.reshape(-1,)

len(y_train)

576

In [113]:
model = KNeighborsClassifier(17)

In [114]:
model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=17, p=2,
           weights='uniform')

In [115]:
X_test = pd.read_csv("Diabetes_Xtest.csv").values

In [116]:
X_test.dtype

dtype('float64')

In [117]:
outcome = model.predict(X_test)
list(outcome)

[1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0]

In [118]:
info = {
    "Outcome" : list(outcome)
}

In [119]:
df = pd.DataFrame.from_dict(info)

In [120]:
df

     Outcome
0          1
1          0
2          0
3          0
4          0
5          0
6          1
7          0
8          0
9          0
10         1
11         0
12         1
13         0
14         0
15         0
16         0
17         1
18         1
19         1
20         0
21         0
22         0
23         1
24         0
25         0
26         0
27         0
28         0
29         0
..       ...
162        0
163        0
164        0
165        0
166        0
167        1
168        0
169        0
170        0
171        0
172        0
173        1
174        0
175        0
176        0
177        0
178        1
179        1
180        0
181        0
182        1
183        0
184        1
185        0
186        0
187        0
188        0
189        1
190        0
191        0

[192 rows x 1 columns]

In [121]:
df.to_csv("info.csv")